### ISSUE TITLE
NIL is on both Constants and Functions

### ISSUE THREAD

**Issue by 1997tn** [paaguti/textadept-modula-lexers#1]
Please have a look at the Modula-3 lexer. Thank you.

**Comment by paaguti** [comment]
Fork, correct and create a PR ;-) That’s the way to learn and contribute;-)PAEnviado desde mi iPhoneEl 25 ene 2023, a las 19:16, 1997tn ***@***.***> escribió:﻿
Please have a look at the Modula-3 lexer. Thank you.
